In [3]:
pip install joblib

Requirement already satisfied: joblib in c:\users\user\appdata\local\programs\python\python314\lib\site-packages (1.5.3)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error,r2_score,mean_squared_error
from sklearn.linear_model import LinearRegression
import joblib

In [5]:
df = pd.read_csv("sales.csv")
df

,Marketing_Spend,Store_Size,Month_Number,Competitor_Price_Index,Holiday_Flag,Sales
0,20795,302,6,0.99,0,158101
1,5860,291,2,0.91,1,87796
2,43158,84,8,1.02,1,219061
3,49732,264,8,0.86,0,299134
4,16284,386,1,1.14,1,137693
...,...,...,...,...,...,...
495,48404,158,7,1.20,1,253307
496,25491,195,8,1.10,0,163832
497,43494,160,6,0.84,0,268791
498,8373,277,6,0.92,0,87259
499,17161,160,5,0.84,0,123237

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Marketing_Spend         500 non-null    int64
 1   Store_Size              500 non-null    int64
 2   Month_Number            500 non-null    int64
 3   Competitor_Price_Index  500 non-null    float64
 4   Holiday_Flag            500 non-null    int64
 5   Sales                   500 non-null    int64
dtypes: float64(1), int64(5)
memory usage: 23.6 KB

In [8]:
df.describe()

,Marketing_Spend,Store_Size,Month_Number,Competitor_Price_Index,Holiday_Flag,Sales
count,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000
mean,26549.188000,269.526000,6.286000,1.000540,0.228000,173734.808000
std,13415.345688,129.663065,3.354207,0.117603,0.419963,70406.506237
min,5161.000000,50.000000,1.000000,0.800000,0.000000,21880.000000
25%,14252.000000,160.000000,3.000000,0.900000,0.000000,117449.500000
50%,26876.000000,268.000000,6.000000,1.010000,0.000000,171599.500000
75%,37586.500000,387.250000,9.000000,1.100000,0.000000,226941.500000
max,49974.000000,499.000000,12.000000,1.200000,1.000000,340500.000000

In [9]:
x = df[['Marketing_Spend','Store_Size','Month_Number']]
y = df['Sales']

In [10]:
print(x.shape)

(500, 3)

In [12]:
print(y.shape)

(500,)

In [13]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [14]:
my_model = LinearRegression()
my_model.fit(x_train,y_train)

LinearRegression()

In [15]:
y_pred = my_model.predict(x_test)
y_pred

array([132422.80135738, 211613.86739672, 174617.6176915 , 191652.25637694,
        60539.29158832, 170393.32359717,  99989.74014619, 186019.62783502,
        94440.88337333, 247835.78219779, 259828.65927019, 151593.60580596,
       115794.8218669 , 121729.4722285 ,  98086.08852899,  43536.54647348,
       259085.68622345, 234123.94105435, 124313.38758273, 162582.5715805 ,
       219263.16285705,  59369.04633961, 201812.00684439, 266769.40228719,
       243878.45623908,  97811.37807964, 235862.40858202, 208301.95153631,
       139837.55365752, 169863.06286108, 186997.65192219, 266722.49919985,
       174322.77744308, 216711.04669158, 220038.98550894, 195528.15267303,
       124669.29547178, 217158.25192882, 298628.91805183, 313669.97427844,
       297325.0831023 , 250426.97492509, 254511.20152721, 173932.49825908,
       200314.87543335, 226821.40441279, 150837.61831469, 249807.77412718,
       192969.65053033, 211964.1885457 , 258915.07385862, 256486.62579554,
       190148.88258187, 116445.91305097,  85951.38080673, 273261.45176341,
       274125.90917375, 188364.94923361,  91437.11072289,  38194.47571741,
       172638.36205192, 132912.79702676, 239399.87780031,  63914.82564673,
       225897.46928024, 147229.82873388, 236671.42620593, 302474.87290993,
        89084.56910948, 193633.80021011, 272964.10451395, 245548.38891392,
       203554.88762911,  68160.16000645, 168617.34500122, 185014.50775311,
       151031.29671377,  99719.08509669, 197003.16159403, 220419.14799808,
       264106.94945436, 174274.29930888,  39436.3766721 ,  54577.85402815,
       311537.12103303, 147597.33843689, 241828.63728821, 177549.76341782,
       150589.65237174, 141087.75123858, 183295.26097815, 256131.46437853,
       142045.99120193, 176953.36341432, 214991.90239567, 168808.36050218,
       152938.07329369, 181284.80139013, 153639.93312582, 110144.16648477])

In [16]:
mse = mean_squared_error(y_test,y_pred)
mse

322527652.85699296

In [17]:
from math import sqrt

In [18]:
rmse = sqrt(mse)
rmse

17959.054898768838

In [19]:
r2 = r2_score(y_test,y_pred)
r2

0.9323729073817951

In [21]:
joblib.dump(my_model,"sales.joblib")

['sales.joblib']

In [22]:
joblib.dump(list(x.columns),'sales_features.joblib')

['sales_features.joblib']

In [23]:
pip install joblib,numpy,fastapi,pydantic,scikit_learn

Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip
ERROR: Invalid requirement: 'joblib,numpy,fastapi,pydantic,scikit_learn': Expected end or semicolon (after name and no valid version specifier)
    joblib,numpy,fastapi,pydantic,scikit_learn
          ^

In [24]:
from fastapi import FastAPI
from pydantic import BaseModel
import joblib
import numpy as np

In [25]:
my_model=joblib.load('sales.joblib')
feature_names = joblib.load('sales_features.joblib')

In [26]:
sales = FastAPI(title='sales.API')

In [28]:
class SalesFeatures(BaseModel):
    Marketing_Spend: float
    Store_Size:float
    Month_Number:int

In [29]:
@ sales.get('/')
def root():
    return{'message':'sales api online!!!'}

In [32]:
@ sales.post('/')
def predict_sales(data:SalesFeatures):
    x = np.array([getattr(data,f) for f in feature_names ])
    prediction = my_model.predict(x)[0]
    return{'predict_sales':float(prediction)}